spring:
  application:
    name: eureka-server-Infra

  output:
    ansi:
      enabled: ALWAYS

server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"


