/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/delivery-register` | `/delivery-register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pending-approval` | `/pending-approval`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/role-selection` | `/role-selection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/active-delivery` | `/active-delivery`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/delivery-register` | `/delivery-register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/pending-approval` | `/pending-approval`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/role-selection` | `/role-selection`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/active-delivery` | `/active-delivery`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/delivery-register${`?${string}` | `#${string}` | ''}` | `/delivery-register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/pending-approval${`?${string}` | `#${string}` | ''}` | `/pending-approval${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/role-selection${`?${string}` | `#${string}` | ''}` | `/role-selection${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/active-delivery${`?${string}` | `#${string}` | ''}` | `/active-delivery${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/delivery-register` | `/delivery-register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pending-approval` | `/pending-approval`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/role-selection` | `/role-selection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/active-delivery` | `/active-delivery`; params?: Router.UnknownInputParams; };
    }
  }
}
