spring:
  application:
    name: authentication-service

  output:
    ansi:
      enabled: ALWAYS

  keycloak:
    token-url: ${KEYCLOAK_TOKEN_URL}
    client-id: ${KEYCLOAK_CLIENT_ID}
    client-secret: ${KEYCLOAK_CLIENT_SECRET}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: REDIS

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"
