version: '3'
services:
  bff-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI=http://discovery-service:8761/eureka
      - ZIPKIN_URL=http://zipkin:9411
    depends_on:
      - discovery-service
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
