plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.10'
}

group = 'com.github.dimitryivaniuta'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    bootBom = '3.5.10'
    lombokVersion = '1.18.42'
    testcontainersBom = '1.21.4' // stable line; avoid mixing BOMs
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    implementation "org.apache.commons:commons-compress:1.28.0"
    // Spring Boot BOM (versions for starters/flyway/postgres/kafka)
    implementation platform("org.springframework.boot:spring-boot-dependencies:${bootBom}")
    testImplementation platform("org.springframework.boot:spring-boot-dependencies:${bootBom}")

    // Testcontainers BOM (single source of truth)
    testImplementation platform("org.testcontainers:testcontainers-bom:${testcontainersBom}")

    // --- App ---
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly  'org.postgresql:postgresql'

    // --- Lombok ---
    compileOnly         "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly     "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // --- Tests ---
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.testcontainers:kafka'

    testImplementation 'org.awaitility:awaitility:4.3.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
