spring:
  application:
    name: cloud-gateway

  output:
    ansi:
      enabled: ALWAYS

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_URI}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${GATEWAY_PORT}

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"
