spring:
  application:
    name: restaurants-service

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://${RESTAURANTS_DB_HOST}:${RESTAURANTS_DB_PORT}/${RESTAURANTS_DB_NAME}
    username: ${RESTAURANTS_DB_USER}
    password: ${RESTAURANTS_DB_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: REDIS

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}
