package com.github.dimitryivaniuta.audittrail.domain;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

/**
 * Append-only audit record.
 *
 * <p>Records are tamper-evident via a chained HMAC hash:</p>
 * <ul>
 *   <li>{@code prevHash} stores the previous record hash (per tenant chain).</li>
 *   <li>{@code hash} stores the current record hash computed over record fields + {@code prevHash}.</li>
 * </ul>
 *
 * <p>DB-level triggers (Flyway migration) reject UPDATE/DELETE operations to enforce immutability.</p>
 */
@Entity
@Table(name = "audit_records",
        indexes = {
                @Index(name = "idx_audit_records_tenant_id_id", columnList = "tenant_id, id"),
                @Index(name = "idx_audit_records_created_at", columnList = "created_at")
        },
        uniqueConstraints = {
                @UniqueConstraint(name = "uq_audit_records_tenant_event_id", columnNames = {"tenant_id", "event_id"})
        })
@Getter
@Setter
@NoArgsConstructor
public class AuditRecordEntity {

    /**
     * Surrogate primary key; also defines append order.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Tenant id for multi-tenant deployments. Hash chain is per tenant.
     */
    @Column(name = "tenant_id", nullable = false, length = 64)
    private String tenantId;


    /**
     * Per-tenant sequence number for strong ordering in the hash chain.
     */
    @Column(name = "seq", nullable = false)
    private long seq;

    /**
     * Caller-provided event id (idempotency) or generated by service.
     */
    @Column(name = "event_id", nullable = false, columnDefinition = "uuid")
    private UUID eventId;

    /**
     * Who initiated the action (user, service, etc).
     */
    @Column(name = "actor", nullable = false, length = 256)
    private String actor;

    /**
     * Logical action (e.g. ORDER_CREATED, ROLE_ASSIGNED).
     */
    @Column(name = "action", nullable = false, length = 128)
    private String action;

    /**
     * Resource type (e.g. ORDER, USER, ROLE).
     */
    @Column(name = "resource_type", nullable = false, length = 128)
    private String resourceType;

    /**
     * Resource identifier (string to support UUIDs and composite ids).
     */
    @Column(name = "resource_id", nullable = false, length = 256)
    private String resourceId;

    /**
     * Correlation id (trace id) for cross-service log correlation.
     */
    @Column(name = "correlation_id", length = 128)
    private String correlationId;

    /**
     * Additional record details stored as JSONB.
     */
    @Column(name = "data", nullable = false, columnDefinition = "jsonb")
    private String dataJson;

    /**
     * Timestamp assigned on insert.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Hash algorithm name (e.g. HmacSHA256).
     */
    @Column(name = "hash_alg", nullable = false, length = 32)
    private String hashAlg;

    /**
     * Key id used for computing {@link #hash}.
     */
    @Column(name = "key_id", nullable = false, length = 32)
    private String keyId;

    /**
     * Previous record hash (per tenant).
     */
    @Column(name = "prev_hash", length = 128)
    private String prevHash;

    /**
     * Current record hash (hex).
     */
    @Column(name = "hash", nullable = false, length = 128)
    private String hash;
}
