import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@shared/ui/components/ui/card";
import { Input } from "@shared/ui/components/ui/input";
import { type JSX } from "react";

interface ParameterViewerProps {
  title: string;
  subTitle: string;
  paramsJSON: string | null;
}

function ParameterViewer({
  title,
  subTitle,
  paramsJSON,
}: Readonly<ParameterViewerProps>): JSX.Element {
  const params = (paramsJSON ? JSON.parse(paramsJSON) : undefined) as
    | Record<string, string>
    | undefined;

  return (
    <Card>
      <CardHeader className="rounded-lg rounded-b-none border-b py-4 bg-gray-50 dark:bg-background">
        <CardTitle className="text-base capitalize">{title}</CardTitle>
        <CardDescription className="text-muted-foreground text-sm capitalize">
          {subTitle}
        </CardDescription>
      </CardHeader>
      <CardContent className="py-4">
        <div className="flex flex-col gap-2">
          {(!params || Object.keys(params).length === 0) && (
            <p className="text-muted-foreground text-sm">
              No parameters generated by this phase
            </p>
          )}
          {params
            ? Object.entries(params).map(([key, value]) => (
                <div
                  className="flex justify-between items-center space-y-1"
                  key={key}
                >
                  <p className="text-sm text-muted-foreground flex-1 basis-1/3">
                    {key}
                  </p>
                  <Input
                    className="flex-1 basis-2/3"
                    readOnly
                    value={String(value)}
                  />
                </div>
              ))
            : null}
        </div>
      </CardContent>
    </Card>
  );
}

export default ParameterViewer;
