spring:
  application:
    name: notifications-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI}

  rabbitmq:
    username: ${NOTIFICATIONS_RABBITMQ_USERNAME}
    password: ${NOTIFICATIONS_RABBITMQ_PASSWORD}
    host: ${NOTIFICATIONS_RABBITMQ_HOST}
    port: ${NOTIFICATIONS_RABBITMQ_PORT}
    order-confirmation-queue: ${NOTIFICATIONS_RABBITMQ_ORDER_CONFIRMATION_QUEUE}
    payment-approved-queue: ${NOTIFICATIONS_RABBITMQ_PAYMENT_APPROVED_QUEUE}
    delivery-ready-queue: ${NOTIFICATIONS_RABBITMQ_DELIVERY_READY_QUEUE}

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

