apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017"
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  KEYCLOAK_HOST: "keycloak"
  KEYCLOAK_PORT: "8080"
  KEYCLOAK_REALM: "ecommerce"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
