# ----------------------------------------
# Server Configuration
# ----------------------------------------
server.port=8082
spring.application.name=asset-service

# ----------------------------------------
# Database connection
# ----------------------------------------
spring.datasource.url=jdbc:mariadb://localhost:3307/ams
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ----------------------------------------
# Flyway
# ----------------------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ----------------------------------------
# JPA / Hibernate
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ----------------------------------------
# Security
# ----------------------------------------
spring.security.user.name=admin
spring.security.user.password=admin
 
# ---------------------------------------- 
# Service URLs for inter-service communication 
# ---------------------------------------- 
service.user.url=http://localhost:8081 
service.request.url=http://localhost:8083 
service.history.url=http://localhost:asset-service0 

# ----------------------------------------
# Logging
# ----------------------------------------
logging.level.com.xrs.assetmanagementsystem=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
